---
app:
  kafka:
    management-topic-name: management-data
    create-topics: false
  microservices:
    storage-adapter:
      base-url: http://localhost:9324
      messages-endpoint: ${app.microservices.storage-adapter.base-url}/message
    email-service:
      base-url: http://localhost:18787
      messages-endpoint: ${app.microservices.email-service.base-url}/email/sendType
  activemq:
    queue-name: management-data  

# Spring configuration
spring:
  kafka:
    bootstrap-servers:
      - localhost:29092
    consumer:
      bootstrap-servers:
        - localhost:29092
      group-id: event-processor
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
    packages:
      # take care with security problems // spring.activemq.packages.trusted=<package1>,<package2>,<package3>  
      trust-all: true
  jms:
    pub-sub-domain: true

## Actuator
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /management
  server:
    port: 9321

## In case of configure web endpoints, remove it or change port number
server:
  port: ${management.server.port}
